/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Base;
import Controller.IRateDAO;
import Controller.OpenPassbookDAO;
import Controller.TinhLai;
import Controller.TypePassbookDAO;
import Model.Passbook;
import java.util.Date;

/**
 *
 * @author ngocn
 */
public class infoPassbook extends javax.swing.JFrame {

    /**
     * Creates new form infoPassbook
     */
    private Passbook passbook = null;

    public infoPassbook(Passbook passbook) {
        initComponents();
        this.passbook = passbook;
        setView();
    }

    public void setView() {
        iDP.setText(String.valueOf(passbook.getID()));
        CMT.setText(passbook.getCustomerID());
        tiengoc.setText(String.valueOf(passbook.getDepositsOriginal()));
        typePassbook.setText(TypePassbookDAO.getNameTypeByID(passbook.getTypeID()));

        String kyhan = String.valueOf(IRateDAO.Instance.getKyHanByID(passbook.getTypePeriod()));
        period.setText(kyhan + " Tháng");

        String lai = null;
        if (IRateDAO.Instance.getKyHanByID(passbook.getTypePeriod()) == 0) {
            lai = Double.toString(IRateDAO.Instance.getLaiSuatKhongKyHan());

        } else {
            lai = Double.toString(IRateDAO.Instance.getLaiSuatCoKyHan(IRateDAO.Instance.getKyHanByID(passbook.getInterestRateID())));
        }
        laiSuat.setText(lai + "%");
        openDate.setText(Base.Instance.dateToStringShow(passbook.getOpenDate()));
        expDate.setText(Base.Instance.dateToStringShow(passbook.getExpDate()));

        double tienlai = TinhLai(passbook.getExpDate(), new Date(), Double.parseDouble(lai), Integer.parseInt(kyhan), passbook.getDepositsOriginal());
        tienLai.setText(Double.toString(tienlai));
    }

    public double TinhLai(Date hanRut, Date ngayRut, Double laiSuat, int kyhan, long soTienGui) {
        long ngaythuc = TinhLai.ngayThuc(ngayRut, hanRut);
        System.out.println(ngaythuc);

        return TinhLai.TinhLai(ngaythuc, hanRut, ngayRut, laiSuat, kyhan, soTienGui);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iDP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CMT = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tiengoc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        typePassbook = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        period = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        openDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        expDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        laiSuat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tienLai = new javax.swing.JLabel();
        withDraw = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chi tiết sổ tiết kiệm");
        setLocation(new java.awt.Point(500, 200));
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin sổ tiết kiệm");

        jLabel2.setText("Mã sổ: ");

        iDP.setText("Mã sổ");

        jLabel3.setText("Mã khách hang:");

        CMT.setText("Mã Khách Hnagf");

        jLabel4.setText("Tiền gửi gốc:");

        tiengoc.setText("despo");

        jLabel5.setText("Loại sổ:");

        typePassbook.setText("loại sổ");

        jLabel6.setText("Kỳ hạn:");

        period.setText("Kỳ hạn");

        jLabel7.setText("Ngày mở:");

        openDate.setText("Ngày mở");

        jLabel8.setText("Ngày hết hạn:");

        expDate.setText("Ngày hết hạn");

        jLabel9.setText("Lãi suất:");

        laiSuat.setText("Lãi suất");

        jLabel10.setText("Lãi nếu rút tới hiện tại:");

        tienLai.setText("Tiền lãi");

        withDraw.setText("Rút sổ");

        back.setText("Quay lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(209, 209, 209))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(withDraw)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(jLabel10))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(openDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CMT, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(tiengoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typePassbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(period, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laiSuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tienLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(back)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(iDP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CMT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tiengoc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(typePassbook))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(period))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(laiSuat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(openDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(expDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tienLai))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withDraw)
                    .addComponent(back))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CMT;
    private javax.swing.JButton back;
    private javax.swing.JLabel expDate;
    private javax.swing.JLabel iDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel laiSuat;
    private javax.swing.JLabel openDate;
    private javax.swing.JLabel period;
    private javax.swing.JLabel tienLai;
    private javax.swing.JLabel tiengoc;
    private javax.swing.JLabel typePassbook;
    private javax.swing.JButton withDraw;
    // End of variables declaration//GEN-END:variables
}
